### ISSUE TITLE
PDF417: ArrayIndexOutOfBoundsException: Index 2700 out of bounds for length 2700

### ISSUE THREAD

**Issue by uwolfer** [woo-j/OkapiBarcode#104]
With the attached data set with `setContent(byte[])` I am able to reproduce the following exception:
```
java.lang.ArrayIndexOutOfBoundsException: Index 2700 out of bounds for length 2700
	at uk.org.okapibarcode.backend.Pdf417.processBytes(Pdf417.java:1670)
	at uk.org.okapibarcode.backend.Pdf417.processPdf417(Pdf417.java:817)
	at uk.org.okapibarcode.backend.Pdf417.encode(Pdf417.java:778)
	at uk.org.okapibarcode.backend.Symbol.setContent(Symbol.java:547)
	at uk.org.okapibarcode.backend.Pdf417.setContent(Pdf417.java:763)
```

Reproduction code:
```java
byte[] bytes = Files.readAllBytes(new File("./data.txt").toPath());
Pdf417 symbolTemplate = new Pdf417();
symbolTemplate.setContent(bytes);
```
[data.txt](https://github.com/woo-j/OkapiBarcode/files/14321594/data.txt)

**Comment by gredler** [comment]
OK, it doesn't look like there's anything special about the data per se, just that it's larger than the buffer allocated internally (which itself is already much larger than the maximum allowed codeword count). The fix will be to throw an `OkapiInputException` in this case instead of an `ArrayOutOfBoundsException` (still an error, but clearer and nicer).

**Comment by uwolfer** [comment]
Thanks for the change, I can confirm that this plays together nicely with https://github.com/woo-j/OkapiBarcode/pull/103.
