### ISSUE TITLE
NullPointerException while using ChannelCode

### ISSUE THREAD

**Issue by karstenw-ro** [woo-j/OkapiBarcode#94]
Since updating to Okapi 0.3.3 Channel Codes always throw an NPE, this did not occur in version 0.3.2.

Source:
```
import uk.org.okapibarcode.backend.ChannelCode;

public class ChannelcodeNPE {
    public static  void main(String[] args) {
        ChannelCode cc = new ChannelCode();
        cc.setContent("123456");
    }
}
```

Stacktrace:
```
Exception in thread "main" java.lang.NullPointerException
	at uk.org.okapibarcode.backend.Symbol.plotSymbol(Symbol.java:657)
	at uk.org.okapibarcode.backend.Symbol.setContent(Symbol.java:530)
	at ChannelcodeNPE.main(ChannelcodeNPE.java:6)
```

**Comment by gredler** [comment]
Thanks for the bug report! Ironic that we had 15+ tests for various different scenarios, but none for this most basic of use cases.
